---
title: "Primer Reporte en R Markdown"
author: "Juan Pablo Tamez 000131958"
output: html_document
---

###Introducción al formato R Markdown

### Introducción al formato R Markdown

Ejemplo elaborado en `r date()`.

```{r Paquetes}
library(ggmap)
```

```{r GenerarDatos, message=FALSE}
# Llenar información (sólo lo que está entre "").
clave.unica <- rep("131958",3)
# 1: Si es mixto, 0: no lo es.
es.mixto <- c(universidad = 1, preparatoria = 0, secundaria = 0)
# Llenar con la dirección.
universidad <- geocode("ITAM")
preparatoria <- geocode("Av. de las Torres No. 131. Torres de Potrero, México D.F. 01780")
secundaria <- geocode("Av. de las Torres No. 131. Torres de Potrero, México D.F. 01780")
# Generamos la información
educacion <- rbind(universidad, preparatoria, secundaria)
educacion <- cbind(clave.unica, es.mixto, educacion)
```

```{r ObtenciónCoordenadasYMapas, warning=FALSE, message=FALSE}
limites <- make_bbox(lon, lat, educacion, f = 0.7)
mapa <- get_map(location = limites, 
                maptype = "roadmap", 
                source = "google")
```

```{r GraficarLocalizaciones, echo=FALSE}
ggmap(mapa) + 
geom_point(data = educacion, 
           aes(x = lon, y = lat), 
           size = 4, alpha = 0.6, colour = "red")
```